export const MOCK_TEMAS = [
  "Filmes",
  "Desenhos Animados",
  "Personagens Bíblicos",
  "Profissões",
  "Países",
  "Super-heróis",
  "Animais",
  "Esportes",
  "Comidas",
  "Instrumentos Musicais",
  "Objetos",
  "Vários",
  "Animais",
  "Esportes",
  "Ações",
];
